#! /bin/sh

# Start sxhkd (Key manager)
pgrep -x sxhkd > /dev/null || sxhkd &

# --- Monitors Settings ---
# Automatically detects the monitor and creates 10 workspaces
bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9 10

# --- Appearance  ---
bspc config border_width         2
bspc config window_gap           6
bspc config top_padding          36
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colours  
bspc config normal_border_color  "#3b4252"
bspc config active_border_color  "#6a3067"
bspc config focused_border_color "#6a3067"
bspc config presel_feedback_color "#9a3732"

bspc config pointer_modifier mod4

# --- Window Rules ---
# e.g. If you want Gimp to always float
# bspc rule -a Gimp state=floating
bspc rule -a Flameshot state=floating manage=off
bspc rule -a Rofi border=off
bspc rule -a gnome-calculator state=floating center=on

# --- Autostart ---
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
nm-applet &
picom &
nitrogen --restore &
redshift &
xss-lock --transfer-sleep-lock -- i3lock --nofork &
# Kill the Zorin/XFCE/GNOME notifications daemon to avoid conflicts
pkill -x xfce4-notifyd
pkill -x notify-osd
dunst &
# Iniciar o KDE Connect e o indicador
/usr/lib/x86_64-linux-gnu/libexec/kdeconnectd &
kdeconnect-indicator &

# --- Polybar ---
$HOME/.config/polybar/launch.sh --forestmodular &
